version: "3"
services:
  node-red:
    image: "nodered/node-red-docker"
    ports:
      - "${NODE_RED_PORT}:${NODE_RED_PORT}"
    networks: 
      - hot-jobs-network
    volumes:
      - ${NODE_RED_VOLUME_PATH}:/data
  rabbit-mq:
    image: "rabbitmq:management"
    networks: 
      hot-jobs-network:
        aliases: 
          - hst-rabbit-mq
    ports:
      - ${RABBITMQ_MANAGEMENT_PORT}:${RABBITMQ_MANAGEMENT_PORT}
  mongo:
    image: "mongo"
    ports:
      - "${MONGO_PORT}:${MONGO_PORT}"
    networks:
      hot-jobs-network:
        aliases: 
          - ${MONGO_HOST}
    volumes:
      - ${MONGO_VOLUME_PATH}:/data
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - ${MONGO_EXPRESS_PORT}:${MONGO_EXPRESS_PORT}
    networks: 
      - hot-jobs-network
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      ME_CONFIG_MONGODB_SERVER: ${MONGO_HOST}
networks:
  hot-jobs-network:
