version: "3"
services:
  node-red:
    image: "nodered/node-red-docker"
    ports:
      - "1880:1880"
    networks: 
      - hot-jobs-network
  rabbit-mq:
    image: "rabbitmq:3"
    networks: 
      hot-jobs-network:
        aliases: 
          - hst-rabbit-mq
  rabbit-management-plugin:
    image: "rabbitmq:3-management"
    ports: 
      - "15672:15672"
networks:
  hot-jobs-network:
